ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "syncMode" TEXT NOT NULL DEFAULT 'auto';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "syncBackendUrl" TEXT NOT NULL DEFAULT '';
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "syncTokenEnc" TEXT;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "syncIntervalMinutes" INTEGER NOT NULL DEFAULT 15;
